# Generated by Django 3.1 on 2021-05-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('username', models.CharField(default='', max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('likebyuserby', models.CharField(default='', max_length=50)),
                ('disbyuser', models.CharField(default='', max_length=50)),
                ('qtn', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='showdata.showdata')),
            ],
        ),
    ]
